# Generated by Django 3.2.4 on 2021-07-05 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0002_auto_20210628_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
