# Generated by Django 3.2.4 on 2021-07-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0004_rename_total_cartdetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='price',
        ),
    ]
