# Generated by Django 3.2.4 on 2021-07-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
