# Generated by Django 3.2.4 on 2021-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0007_auto_20210705_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sessions',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
