# Generated by Django 3.2.4 on 2021-07-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0008_cart_sessions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='sessions',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_cart',
            new_name='total',
        ),
        
    ]
