# Generated by Django 3.2.4 on 2021-07-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0009_auto_20210705_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartdetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
